language: node_js

sudo: false

node_js:
    # Current
    - "6.1"
    - "6.0"
    - "5.9"
    # LTS
    - "4.4"
    # Maintenance
    - "0.12"
    - "0.10"

script:
    - npm test
    - npm run lint
    - npm run coverage && npm run coverage-upload

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
