language: node_js

sudo: false

node_js:
    - "iojs-v2.4.0"
    - "iojs-v3.1.0"
    - "iojs-v3.2.0"
    - "0.12"

script:
    - npm test
    - npm run lint
    - npm run coverage && npm run coverage-upload

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
