language: node_js

sudo: false

node_js:
    # Current
    # - "6.9" # The current is the last LTS
    # LTS
    - "6.9"
    - "4.4"

script:
    - npm test
    - npm run lint
    - npm run coverage && npm run coverage-upload

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
