language: node_js

sudo: false

node_js:
    - "5.7"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
    - "5.2"
    - "5.1"
    - "5.0"
    - "4.3"
    - "4.2"
    - "0.12"

script:
    - npm test
    - npm run lint
    - npm run coverage && npm run coverage-upload

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
